[package]
name = "nok"
version = "0.1.0"
edition = "2021"
authors = ["Devin AI"]
description = "A terminal-based virtual office application"

[dependencies]
ratatui = { version = "0.26.0", features = ["all-widgets"] }
crossterm = "0.27.0"
rodio = "0.17.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
rand = "0.8"
